//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace THNETII.PubTrans.AvinorFlydata.Bindings.XsdAutoGenerated {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class airportNames {
        
        private airportNamesAirportName[] airportNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("airportName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public airportNamesAirportName[] airportName {
            get {
                return this.airportNameField;
            }
            set {
                this.airportNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class airportNamesAirportName {
        
        private string codeField;
        
        private string nameField;
        
        private string icaoField;
        
        private string shortname8Field;
        
        private string shortname15Field;
        
        private string name_ukField;
        
        private string shortname8_ukField;
        
        private string shortname15_ukField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string icao {
            get {
                return this.icaoField;
            }
            set {
                this.icaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shortname8 {
            get {
                return this.shortname8Field;
            }
            set {
                this.shortname8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shortname15 {
            get {
                return this.shortname15Field;
            }
            set {
                this.shortname15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name_uk {
            get {
                return this.name_ukField;
            }
            set {
                this.name_ukField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shortname8_uk {
            get {
                return this.shortname8_ukField;
            }
            set {
                this.shortname8_ukField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shortname15_uk {
            get {
                return this.shortname15_ukField;
            }
            set {
                this.shortname15_ukField = value;
            }
        }
    }
}
