//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace THNETII.PubTrans.AvinorFlydata.Bindings.XsdAutoGenerated {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class gateStatuses {
        
        private gateStatusesGateStatus[] gateStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gateStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public gateStatusesGateStatus[] gateStatus {
            get {
                return this.gateStatusField;
            }
            set {
                this.gateStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class gateStatusesGateStatus {
        
        private string codeField;
        
        private string gateStatusTextEnField;
        
        private string gateStatusTextNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gateStatusTextEn {
            get {
                return this.gateStatusTextEnField;
            }
            set {
                this.gateStatusTextEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gateStatusTextNo {
            get {
                return this.gateStatusTextNoField;
            }
            set {
                this.gateStatusTextNoField = value;
            }
        }
    }
}
