//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace THNETII.PubTrans.AvinorFlydata.Bindings.XsdAutoGenerated {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class flightStatuses {
        
        private flightStatusesFlightStatus[] flightStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flightStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public flightStatusesFlightStatus[] flightStatus {
            get {
                return this.flightStatusField;
            }
            set {
                this.flightStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class flightStatusesFlightStatus {
        
        private string codeField;
        
        private string statusTextEnField;
        
        private string statusTextNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string statusTextEn {
            get {
                return this.statusTextEnField;
            }
            set {
                this.statusTextEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string statusTextNo {
            get {
                return this.statusTextNoField;
            }
            set {
                this.statusTextNoField = value;
            }
        }
    }
}
